'use strict';
module.exports = {
  YELP_FUSION_GET_REVIEWS_URL: 'businesses/{}/reviews',
  YELP_GET_BUSINESSES_WITH_CATEGORIES_URL: 'businesses/search',
  YELP_FUSION_GET_BUSINESS_INFO_URL: 'businesses',
  PROMISE_FULFILLED: 'fulfilled',
  YELP_ERROR: 'E_500',
  INTERNAL_ERROR: 'I_500',
  YELP_REVIEWS_ERROR: 'Unable to get reviews of given business',
  YELP_BUSINESS_ERROR: 'Unable to get business info',
  RATING: 'rating',
  BEARER: 'Bearer ',
  EMPTY: '',
  APP_NAME: 'Simplrr',
  DEV: 'development',
  LOG_LEVEL_INFO: 'info',
  LOG_LEVEL_ERROR: 'error',
  ICE_CREAM_CATEGORY: 'icecream',
  REDWOOD_CITY: 'Redwood City',
  SORT_BY_RATING: 'rating',
};
